settings:
  legacy:
    # If you want Realize running in a container to detect changes,
    # it must be true (polling).
    force: true
    interval: 1s
schema:
  - name: app-debug
    path: .
    commands:
      build:
        status: true
        # WORKAROUND: The value of the -gcflags option ("all=-N -l") is separated by a space and is interpreted as an error
        # if it is written directly in ".realize.yaml".
        method: ./realize/go-debug-build.sh -o /bin/sample-go-server-debug ./app
      run:
        status: true
        method: /go/bin/dlv
    args:
      - exec
      - /bin/sample-go-server-debug
      - --listen=:2345
      - --headless
      - --api-version=2
      # Run Delve with the uninterrupted setting in the main function.
      # see: https://github.com/derekparker/delve/blob/master/Documentation/faq.md#how-do-i-use-delve-with-docker
      - --continue
      - --accept-multiclient
    watcher:
      paths:
        - /app
      ignored_paths:
        - .git
        - .realize
        - vendor
      extensions:
        - go
      # WORKAROUND: If you don't explicitly kill a child process, Delve and its child don't terminate.
      scripts:
        - type: before
          command: pkill -INT /bin/sample-go-server-debug
          output: true
